version: 2.1
orbs:
  slack: circleci/slack@4.10.1

commands:
  notify_slack_pass:
    steps:
      - slack/notify:
          channel: D02FP5L229G
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":tada::tada::tada: *Success!*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project:*\n${CIRCLE_PROJECT_REPONAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When:*\n$(TZ=Asia/Tokyo date +'%Y/%m/%d %T')"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Job:*\n${CIRCLE_JOB}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${CIRCLE_USERNAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${CIRCLE_BRANCH}"
                    }
                  ]
                }
              ]
            }

  notify_slack_fail:
    steps:
      - slack/notify:
          channel: D02FP5L229G
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":japanese_ogre::japanese_ogre::japanese_ogre: *Failed* :bangbang:"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project:*\n${CIRCLE_PROJECT_REPONAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*When:*\n$(TZ=Asia/Tokyo date +'%Y/%m/%d %T')"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Job:*\n${CIRCLE_JOB}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${CIRCLE_USERNAME}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${CIRCLE_BRANCH}"
                    }
                  ]
                }
              ]
            }

jobs:
  build:
    working_directory: ~/koyolympus
    docker:
      - image: cimg/php:7.4-node
    steps:
      - checkout
      - restore_cache:
          name: restore cache for node
          keys:
            - npm-cache-v1-{{ checksum "koyolympus/package-lock.json" }}
      - restore_cache:
          name: restore cache for composer
          keys:
            - composer-cache-v1-{{ checksum "koyolympus/composer.json" }}
      - run:
          name: npm install
          command: |
            DIR_NODE='./koyolympus/node_modules'
            if [ -d "${DIR_NODE}" ]; then
                echo "[node_modules] directory is already exist, so [npm install] does not run."
            else
                npm --prefix koyolympus install koyolympus
            fi
      - run:
          name: composer install
          command: |
            DIR_COMPOSER='./koyolympus/vendor'
            if [ -d "${DIR_COMPOSER}" ]; then
                echo "[vendor] directory is already exist, so [composer install] does not run."
            else
                composer install -n --prefer-dist --working-dir=./koyolympus
            fi
      - save_cache:
          name: save_cache_node
          key: npm-cache-v1-{{ checksum "koyolympus/package-lock.json"}}
          paths:
            - koyolympus/node_modules
      - save_cache:
          name: save_cache_composer
          paths:
            - koyolympus/vendor
          key: composer-cache-v1-{{ checksum "koyolympus/composer.json" }}
      - run:
          name: npm run production
          working_directory: koyolympus
          command: npm run prod
      - persist_to_workspace:
          name: prepare to pass folders.
          root: koyolympus/
          paths:
            - node_modules/
            - vendor/
      - notify_slack_fail

  style-check:
    docker:
      - image: cimg/php:7.4.26
    steps:
      - checkout
      - attach_workspace:
          at: koyolympus/
      - run:
          name: check PHP code style (PSR12)
          working_directory: koyolympus
          command: vendor/bin/phpcs --standard=phpcs.xml -p ./
      - notify_slack_fail

  larastan:
    docker:
      - image: cimg/php:7.4.26
    steps:
      - checkout
      - attach_workspace:
          at: koyolympus/
      - run:
          name: analyze php code statically
          working_directory: koyolympus
          command: vendor/bin/phpstan analyse
      - notify_slack_fail

  test:
    docker:
      - image: cimg/php:7.4.26
      - image: cimg/mysql:5.7
    environment:
      - DB_CONNECTION: circle_testing
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: install wget git unzip etc...
          command: sudo apt-get install -y wget git unzip libpq-dev libfreetype6-dev libjpeg-dev libpng-dev
      - run:
          name: install pcov
          command: |
            sudo pecl install pcov
      - attach_workspace:
          at: koyolympus/
      - run:
          name: Show PHPUnit Test List
          command: koyolympus/vendor/bin/phpunit --list-tests koyolympus/tests/Unit/
      - run:
          name: prepare .env.testing
          command: |
            echo "APP_KEY=" > .env.testing
            echo CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID > .env.testing
      - run:
          name: generate app_key
          command: php artisan key:generate --env=testing
          working_directory: koyolympus
      - run:
          name: config cache
          command: php artisan config:cache
          working_directory: koyolympus
      - run:
          name: migration
          command: php artisan migrate --env=testing
          working_directory: koyolympus
      - run:
          name: setup Code Climate test-reporter
          working_directory: koyolympus
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: run PHPUnit
          working_directory: koyolympus
          command: |
            ./cc-test-reporter before-build
            vendor/bin/phpunit --coverage-clover clover.xml
            ./cc-test-reporter format-coverage clover.xml --add-prefix koyolympus -t clover -o codeclimate.json
            ./cc-test-reporter upload-coverage -i codeclimate.json
      - notify_slack_fail
      - notify_slack_pass

  deploy:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: install aws cli
          command: sudo pip install awscli
      - run:
          name: run shell script for deploying
          command: .circleci/deploy.sh ${CIRCLE_TAG}
      - notify_slack_fail
      - notify_slack_pass

workflows:
  version: 2
  build_to_deploy:
    jobs:
      - build:
          context: koyolympus
      - style-check:
          context: koyolympus
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - larastan:
          context: koyolympus
          requires:
            - style-check
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - test:
          context: koyolympus
          requires:
            - larastan
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - approval:
          type: approval
          requires:
            - test
          filters:
            tags:
              only: /^v*/
            branches:
              ignore: /.*/
      - deploy:
          context: koyolympus
          requires:
            - approval
          filters:
            tags:
              only: /^v*/
            branches:
              ignore: /.*/
