version: 2
jobs:
  build:
    working_directory: ~/koyolympus
    docker:
      - image: circleci/php:7.3.0-node-browsers
      - image: cimg/node:16.5.0
    steps:
      - checkout
      - restore_cache:
          name: restore_cache_node
          keys:
            - npm-cache-koyolympus-{{ checksum "koyolympus/package-lock.json" }}
            - npm-cache-koyolympus-
      - restore_cache:
          name: restore_cache_composer
          keys:
            - v1-dependencies-{{ checksum "koyolympus/composer.json" }}
            - v1-dependencies-
      - run:
          name: npm install
          command: |
            DIR_NODE='./koyolympus/node_modules'
            if [ -d "${DIR_NODE}" ]; then
                echo "[node_modules] directory is already exist, so [npm install] does not run."
            else
                npm --prefix koyolympus install koyolympus
            fi
      - run:
          name: composer install
          command: |
            cd koyolympus
            ls vendor/
            DIR_COMPOSER='./koyolympus/'
            composer install -n --prefer-dist
            ls vendor/
      - save_cache:
          name: save_cache_node
          key: npm-cache-koyolympus-{{ checksum "koyolympus/package-lock.json"}}
          paths:
            - koyolympus/node_modules
      - save_cache:
          name: restore_cache_composer
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "koyolympus/composer.json" }}
      - run:
          name: npm run production
          working_directory: koyolympus
          command: npm run circle-ci
      - persist_to_workspace:
          root: koyolympus
          paths:
            - node_modules/

  test:
    docker:
      - image: circleci/php:7.3.0-node-browsers
      - image: circleci/mariadb:10.4
    environment:
      - DB_CONNECTION: circle_testing
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensiions install
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: libjpeg etc install
          command: sudo apt-get install -y wget git unzip libpq-dev libfreetype6-dev libjpeg-dev libpng-dev
      - run:
          name: php-gd install
          command: sudo docker-php-ext-configure gd --with-png-dir=/usr/include --with-jpeg-dir=/usr/include
      - run:
          name: add install command
          command: sudo docker-php-ext-install gd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "koyolympus/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist --working-dir=./koyolympus
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "koyolympus/composer.json" }}
      - run:
          name: Show PHPUnit Test List
          command: koyolympus/vendor/bin/phpunit --list-tests koyolympus/tests/Unit/
      - run:
          name: prepare .env.testing
          command: |
            echo "APP_KEY=" > .env.testing
            echo CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID > .env.testing
      - run:
          name: generate app_key
          command: php artisan key:generate --env=testing
          working_directory: koyolympus
      - run:
          name: config cache
          command: php artisan config:cache
          working_directory: koyolympus
      - run:
          name: migration
          command: php artisan migrate --env=testing
          working_directory: koyolympus
      - run:
          name: setup Code Climate test-reporter
          working_directory: koyolympus
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: run PHPUnit
          working_directory: koyolympus
          command: |
            ./cc-test-reporter before-build
            vendor/bin/phpunit --coverage-clover clover.xml tests/Unit/
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
