version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3.0-node-browsers
      - image: circleci/mariadb:10.4
    environment:
      - DB_CONNECTION: circle_testing
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensiions install
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: check file structure
          command: ls -a
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "koyolympus/composer.json" }}
            - v1-dependencies-
      - run: 
          name: change directory
          command: cd koyolympus       
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist --working-dir=./koyolympus
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "koyolympus/composer.json" }}
      - run:
          name: Run PHPUnit
          command: koyolympus/vendor/bin/phpunit
   

