version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: mysql
          - DB_DATABASE: koyolympus_test
          - DB_USERNAME: koyo
          - DB_PASSWORD: olympus

      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_DATABASE: koyolympus_test


    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "koyolympus/composer.json" }}
            - v1-dependencies-

      - run: 
          working_directory: koyolympus
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "koyolympus/composer.json" }}
          paths:
            - ./vendor

      - run: echo "APP_KEY=" > .env.testing
      - run: cd koyolympus
      - run: ls
      - run: php artisan key:generate
      - run: php artisan migrate

      - run: ./vendor/bin/phpunit
