version: 2
jobs:
  build:
    working_directory: ~/koyolympus
    docker:
      - image: cimg/node:16.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-bb-{{ checksum "koyolympus/package-lock.json" }}
            - npm-cache-bb-
      - run:
          name: check if node_modules exists.
          command: cd koyolympus ; ls
      - run:
          name: npm install
          command: |
            DIR='node_modules'
            if [ -d "${dir}"]; then
                echo "[node_modules] directory is already exist, so [npm install] does not run."
            else
                npm --prefix koyolympus install koyolympus
            fi
      - save_cache:
          key: npm-cache-bb-{{ checksum "koyolympus/package-lock.json"}}
          paths:
            - koyolympus/node_modules
      - run:
          name: check if node_modules exists.
          command: cd koyolympus ; ls
      - run:
          name: check node_modules/webpack
          command: cd koyolympus/node_modules/webpack ; ls
      - run:
          name: npm run production
          command: cd koyolympus ; npm run node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
    #   - run:
    #       name: cd public/js
    #       command: cd koyolympus/public/js ; ls

  test:
    docker:
      - image: circleci/php:7.3.0-node-browsers
      - image: circleci/mariadb:10.4
    environment:
      - DB_CONNECTION: circle_testing
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Docker php extensiions install
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: libjpeg etc install
          command: sudo apt-get install -y wget git unzip libpq-dev libfreetype6-dev libjpeg-dev libpng-dev
      - run:
          name: php-gd install
          command: sudo docker-php-ext-configure gd --with-png-dir=/usr/include --with-jpeg-dir=/usr/include
      - run:
          name: add install command
          command: sudo docker-php-ext-install gd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "koyolympus/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist --working-dir=./koyolympus
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "koyolympus/composer.json" }}
      - run:
          name: Show PHPUnit Test List
          command: koyolympus/vendor/bin/phpunit --list-tests koyolympus/tests/Unit/
      - run:
          name: echo .env.testing
          command: echo "APP_KEY=" > .env.testing
      - run:
          name: generate app_key
          command: php artisan key:generate --env=testing
          working_directory: koyolympus
      - run:
          name: config cache
          command: php artisan config:cache
          working_directory: koyolympus
      - run:
          name: migration
          command: php artisan migrate --env=testing
          working_directory: koyolympus
      - run:
          name: Run PHPUnit
          command: koyolympus/vendor/bin/phpunit koyolympus/tests/Unit/

workflows:
  version: 2
  builad_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
